### ISSUE TITLE
Licence ?

### ISSUE THREAD

**Issue by jokesterfr** [bezkoder/vue-upload-files#6]
Hi!
thank you for your work and your great blog posts :)
I'm wondering, what licence do you use for this project? I would like to integrate both this one and the express server in a simple docker image, to ease fast deploys when you need to share files with friends.

Thank you!

**Comment by bezkoder** [comment]
Hi, you can use the source code in your project without worring anything :)
Just don't use it to create tutorial like my tutorial :)

**Comment by jokesterfr** [comment]
Thank you, I'll back link your work in the readme.
